const INTERNATIONAL_TRANSFERS_QUERY_KEYS = Object.freeze({
  ALINMA_EXPRESS_BENEFICIARY: 'ALINMA_EXPRESS_BENEFICIARY',
  WESTERN_UNION_BENEFICIARY: 'WESTERN_UNION_BENEFICIARY',
});

export default INTERNATIONAL_TRANSFERS_QUERY_KEYS;
