const INTERNATIONAL_TRANSFER_QUERY_KEYS = Object.freeze({
  GET_COUNTRIES_AE: 'GET_COUNTRIES_AE',
  GET_AE_METADATA: 'GET_AE_METADATA',
  GET_AE_BANKS: 'GET_AE_BANKS',
  GET_WU_METADATA: 'GET_WU_METADATA',
  GET_WU_REMITTANCE: 'GET_WU_REMITTANCE',
  GET_WU_CURRENCIES: 'GET_WU_CURRENCIES',
  GET_WU_BANKS: 'GET_WU_BANKS',
});

export default INTERNATIONAL_TRANSFER_QUERY_KEYS;
