/**
 * Defines screen names used in navigation.
 */
const enum ScreenNames {
  HOME = 'Home',
  HOME_BASE = 'HomeBase',
  PROFILE = 'Profile',
  SETTINGS = 'Settings',
  HELP_CENTER = 'Help Center',
  MOBILE_IQAMA_VERIFICATION = 'MobileAndIqamaVerification',
  CARDS = 'Cards',
  MARKETPLACE = 'Shop',
  MORE = 'More',
  ADD_PASSCODE = 'Enter Passcode',
  NEW_PASSCODE = 'New Passcode',
  RESET_SUCCESSFUL = 'Reset Successful',
  SET_PASSCODE = 'SetPasscode',
  CONFIRM_PASSCODE = 'ConfirmPasscode',
  REGISTRATION_SUCCESSFUL = 'RegistrationSuccessful',
  LOGIN_VIA_PASSCODE = 'LoginViaPasscode',
  PASSCODE_RECREATED = 'PasscodeRecreatedSuccessfuly',
  ONBOARDING = 'Onboarding',
  SPLASH = 'splash',
  WALLET = 'Wallet',
  DELINK_SUCCESS = 'DelinkSuccess',
  TOP_UP = 'Top Up',
  CARD_VERIFICATION = 'Card Verification',
  TOP_UP_SUCCESS = 'Top Up Success',
  IDENTITY_SUCCESSFUL = 'IdentitySuccessMessage',
  POINTS_REDEMPTIONS = 'PointsRedemption',
  POINTS_REDEMPTIONS_CONFIRMATION = 'PointsRedemptionConfirmation',
  POINTS_REDEMPTIONS_SUCCESS_AND_FAILED = 'PointsRedemptionSuccessAndFailed',
  TOP_UP_IBAN = 'TopUpIBAN',
  TRANSACTIONS_HISTORY = 'TransactionsHistory',
  NEAREST_ATM = 'NearestAtmScreen',
  CARD_ISSUE_CONFIRMATION = 'CardIssueConfirmation',
  WALLET_TRANSFER = 'WalletTransfer',
  ATM_WITHDRAW_QRCODE_SCANNER = 'ATMWithDrawQRCodeScanner',
  SEND_MONEY_QRCODE_SCANNER = 'SendMoneyQRCodeScanner',
  ATM_WITHDRAWALS = 'AtmWithdrawals',
  ATM_WITHDRAW_SUCCESSFUL = 'AtmWithdrawSuccessful',
  CARD_OPTIONS = 'CardOptions',
  CHANGE_PIN_SUCCESS = 'ChangePinSuccess',
  CARD_RENEWAL = 'CardRenewal',
  VIRTUAL_CARD = 'VirtualCard',
  REPLACE_CARD_CHOOSE_ADDRESS = 'ReplaceCardChooseAddress',
  REPLACE_CARD_CONFIRM_DETAILS = 'ReplaceCardConfirmDetails',
  CARD_FEATURES = 'CardFeatures',
  VIRTUAL_CARD_SUCCESS = 'VirtualCardSuccess',
  CARD_RENEWAL_SUCCESS = 'CardRenewalSuccess',
  LOCAL_TRANSFER = 'LocalTransfer',
  STATUS_SUCCESS_SCREEN = 'StatusSuccessScreen',
  SEND_MONEY_FORM = 'SendMoneyForm',
  REPLACE_CARD_SUCCESS = 'ReplaceCardSuccess',
  TRANSFER_SUMMARY = 'TransferSummary',
  INTERNATIONAL_TRANSFER_HISTORY = 'InternationalTransferHistory',
}

export default ScreenNames;
