/**
 * Defines screen names used in navigation.
 */
const enum screenNames {
  HOME = 'Home',
  HOME_BASE = 'HomeBase',
  PROFILE = 'Profile',
  SETTINGS = 'Settings',
  HELP_CENTER = 'Help Center',
  MOBILE_IQAMA_VERIFICATION = 'MobileAndIqamaVerification',
  CARDS = 'Cards',
  MARKETPLACE = 'Shop',
  MORE = 'More',
  ADD_PASSCODE = 'Enter Passcode',
  NEW_PASSCODE = 'New Passcode',
  RESET_SUCCESSFUL = 'Reset Successful',
  SET_PASSCODE = 'SetPasscode',
  CONFIRM_PASSCODE = 'ConfirmPasscode',
  REGISTRATION_SUCCESSFUL = 'RegistrationSuccessful',
  LOGIN_VIA_PASSCODE = 'LoginViaPasscode',
  PASSCODE_RECREATED = 'PasscodeRecreatedSuccessfuly',
  ONBOARDING = 'Onboarding',
  SPLASH = 'splash',
  WALLET = 'Wallet',
  DELINK_SUCCESS = 'DelinkSuccess',
  TOP_UP = 'Top Up',
  CARD_VERIFICATION = 'Card Verification',
  TOP_UP_SUCCESS = 'Top Up Success',
  IDENTITY_SUCCESSFUL = 'IdentitySuccessMessage',
  POINTS_REDEMPTIONS = 'PointsRedemption',
  POINTS_REDEMPTIONS_CONFIRMATION = 'PointsRedemptionConfirmation',
  POINTS_REDEMPTIONS_SUCCESS_AND_FAILED = 'PointsRedemptionSuccessAndFailed',
  TOP_UP_IBAN = 'TopUpIBAN',
  TRANSACTIONS_HISTORY = 'TransactionsHistory',
  CARD_OPTIONS = 'CardOptions',
  CHANGE_PIN_SUCCESS = 'ChangePinSuccess',
  VIRTUAL_CARD = 'VirtualCard',
}

export default screenNames;
