import images from '@app/assets/images';
import { TransactionOperations, TransactionTypes } from '@app/enums/transaction-types.enum';
import { BeneficiaryTransactionItemProps } from './beneficiary-transaction-history.interface';

const beneficiaryHistoryData: BeneficiaryTransactionItemProps[] = [
  {
    name: 'Floyd Miles',
    transaction_type: TransactionTypes.TRANSFER_SEND_MONEY,
    type: TransactionOperations.CREDIT,
    amount: '600',
    beneficiary_nick_name: 'Miles',
    transfer_by: images.nationalBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    fee: '10 SAR',
    vat: '40 SAR',
    total_amount: '3000 SAR',
    bank_name: 'Saudi National Bank',
    bank_image: images.nationalBankLogo,
    bank_account_no: 'EG380019000500000000263180001',
  },
  {
    name: 'Brooklyn Simmons',
    transaction_type: TransactionTypes.TRANSFER_RECEIVED_MONEY,
    type: TransactionOperations.DEBIT,
    amount: '1200',
    sender_nick_name: 'Ahmed Mohamed',
    transfer_by: images.nationalBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    bank_name: 'Saudi National Bank',
    bank_image: images.nationalBankLogo,
    bank_account_no: 'EG380019000500000000263180002',
  },
  {
    name: 'Kristin Watson',
    transaction_type: TransactionTypes.TRANSFER_SEND_MONEY,
    type: TransactionOperations.CREDIT,
    amount: '700',
    beneficiary_nick_name: 'Miles',
    transfer_by: images.rajhiBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    fee: '10 SAR',
    vat: '40 SAR',
    total_amount: '3050 SAR',
    bank_name: 'Al Rajhi Bank',
    bank_image: images.rajhiBankLogo,
    bank_account_no: 'EG380019000500000000263180003',
  },
  {
    name: 'Devon Lane',
    transaction_type: TransactionTypes.TRANSFER_RECEIVED_MONEY,
    type: TransactionOperations.DEBIT,
    amount: '510',
    sender_nick_name: 'Ahmed Mohamed',
    transfer_by: images.rajhiBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    bank_name: 'Al Rajhi Bank',
    bank_image: images.rajhiBankLogo,
    bank_account_no: 'EG380019000500000000263180004',
  },
  {
    name: 'Jacob Jones',
    transaction_type: TransactionTypes.TRANSFER_SEND_MONEY,
    type: TransactionOperations.CREDIT,
    amount: '850',
    beneficiary_nick_name: 'Miles',
    transfer_by: images.alinmaBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    fee: '10 SAR',
    vat: '40 SAR',
    total_amount: '3100 SAR',
    bank_name: 'Alinma Bank',
    bank_image: images.alinmaBankLogo,
    bank_account_no: 'EG380019000500000000263180005',
  },
  {
    name: 'Wade Warren',
    transaction_type: TransactionTypes.TRANSFER_RECEIVED_MONEY,
    type: TransactionOperations.DEBIT,
    amount: '2150',
    sender_nick_name: 'Ahmed Mohamed',
    transfer_by: images.alinmaBankLogo,
    transfer_reason: 'Family and frindes',
    note: 'Hello My dear',
    ref_number: 'FTA35346',
    bank_name: 'Alinma Bank',
    bank_image: images.alinmaBankLogo,
    bank_account_no: 'EG380019000500000000263180006',
  },
];

export default beneficiaryHistoryData;
