import { GetWalletMockProps } from './get-wallet.interface';

const getWalletInfoMock: GetWalletMockProps = {
  data: {
    response: {
      fatherName: 'Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù†',
      qrBeforeLogin: false,
      accountBasicInfoCompleted: true,
      userUnderReview: false,
      walletType: 'C',
      grandFatherName: 'Ø¨Ø§Ø¯',
      basicTier: false,
      addressDetails: {
        poBox: '12333',
        street: 'olayan',
        district: 'testo',
        additionalNumber: '1235',
        buildingNumber: '1234',
        unitNumber: '1235',
      },
      viban: 'SA2305012000000110000952',
      availableBalance: '51217.48',
      createdAt: '2019-01-02',
      limitsDetails: {
        dailyIncomingLimit: '25000',
        dailyRemainingIncomingAmount: '24876.67',
        monthlyRemainingOutgoingAmount: '43177.51',
        monthlyIncomingLimit: '50000',
        dailyRemainingOutgoingAmount: '18177.51',
        dailyOutgoingLimit: '25000',
        monthlyOutgoingLimit: '50000',
        monthlyRemainingIncomingAmount: '49876.67',
      },
      familyName: 'Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù†',
      userPreferences: {
        hasGifts: true,
        hasMoneyRequests: true,
      },
      accountBasicInfo: {
        occupationDesc: ' Ù…Ù‚Ø¯Ù…',
        occupation: '71',
        nationality: 'Saudi Arabia#Ø§Ù„Ø³Ø¹ÙˆØ¯ÙŠØ©',
        jobTitle: null,
        monthlyIncomeAmount: '1',
        incomeAmount: null,
        industry: 'TEST1',
        incomeSource: 'Payroll',
        industryDesc: 'TEST1',
      },
      pep: false,
      bioRecognition: false,
      walletNumber: '10142',
      nationalAddressComplete: true,
      currentBalance: '76579.00',
      bioRecognised: true,
      userContactInfo: {
        owner: null,
        realUser: null,
        cityDesc: 'Ø£Ø­Ø¯ Ø§Ù„Ù…Ø³Ø§Ø±Ø­Ø©',
        address: 'olayan AHAD AL-MASAREHA',
        city: 'AHAD AL-MASAREHA',
        mobileNumber: '0583433324',
        postalCode: '12333',
        preferedLanguage: 'Ar',
        moiRegistred: null,
        townCountry: 'SA',
        email: 'msbinhawshan@alinma.com',
      },
      fullName: 'Ø¨Ø±Ø§Ø¨Ø§ÙƒØ§Ø±Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù†',
      passwordMigrated: true,
      hasVat: false,
      walletTier: 'P',
      firstName: 'Ø¨Ø±Ø§Ø¨Ø§ÙƒØ§Ø±Ø§Ù†',
      dormant: false,
      walletStatus: 'ACTIVE',
      idExpired: false,
      walletRisk: 'L',
      workDetails: {
        occupationDesc: ' Ù…Ù‚Ø¯Ù…',
        occupation: '71',
        jobTitle: null,
        industry: 'TEST1',
        industryDesc: 'TEST1',
      },
    },
    successfulResponse: true,
    status: {
      sessionReference: 'SSPAYC5c2207e5333046a780efc88f0d60fc23',
      code: 'I000000',
      requestReference: '03939829382653694679',
      type: 'SUCCESS',
      desc: 'Alinmapay.walletDetailsInquiry.getWalletDetails.messege.success',
    },
  },
  ok: true,
};

export default getWalletInfoMock;
