import { SadadBillsByStatusMockProps } from './get-sadad-bills-by-status.interface';

const sadadBillsByStatusMock: SadadBillsByStatusMockProps = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
    sessionReference: 'SSPAYC31dea075087d4ef8ae4b3c686eadae13',
    requestReference: '08752626837454636492',
  },
  paginationInfo: {
    matchedRecords: '3',
    sentRecords: '3',
  },
  response: {
    paymentInfoList: [
      {
        amount: '-5850.00',
        dueDateTime: '09-07-2020',
        billCycle: '4253001',
        billId: 'BILL23352CW03ZYZ',
        billIdType: '0',
        billNumOrBillingAcct: '75325875657',
        billerId: '002',
        billerName: '002 - Saudi Electric Company',
        paymentMethod: null,
        paymenType: null,
        checkDigit: null,
        billDesc: 'testelc',
        serviceDescription: null,
        billStatusCode: 'BillOverPd',
        billStatusDesc: 'billOverPaid',
        svcType: 'GOVT',
      },
      {
        amount: '-195.00',
        dueDateTime: '09-07-2020',
        billCycle: '512325',
        billId: 'BILL2335253RFTP3',
        billIdType: '0',
        billNumOrBillingAcct: '84535236012',
        billerId: '044',
        billerName: '044 - Zain',
        paymentMethod: null,
        paymenType: null,
        checkDigit: null,
        billDesc: 'test zain',
        serviceDescription: null,
        billStatusCode: 'BillOverPd',
        billStatusDesc: 'billOverPaid',
        svcType: 'GOVT',
      },
      {
        amount: '-60.00',
        dueDateTime: '09-07-2020',
        billCycle: '4751231',
        billId: 'BILL23352LKN9F3X',
        billIdType: '0',
        billNumOrBillingAcct: '54678905318',
        billerId: '001',
        billerName: '001 - STC',
        paymentMethod: null,
        paymenType: null,
        checkDigit: null,
        billDesc: 'arwa test',
        serviceDescription: null,
        billStatusCode: 'BillOverPd',
        billStatusDesc: 'billOverPaid',
        svcType: 'GOVT',
      },
    ],
  },
  successfulResponse: true,
};

export default sadadBillsByStatusMock;
