import { WalletToWalletTransferMockProps } from './wallet-to-wallet-transfer.interface';

const walletToWalletTransferMock: WalletToWalletTransferMockProps = {
  response: {
    transferRequestsResult: {
      groupedCategories: {
        RECEIVED: [
          {
            amount: '12.00',
            receiverWalletNumber: '10142',
            senderWalletNumber: '20004141',
            receiverName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            trnsDateTime: '2008-04-08T17:17:00',
            bankFeeAmt: null,
            receiverMobile: '0583433324',
            senderMobile: '0523614587',
            feeAmt: null,
            parentRequestID: 'EPY08099J8M75',
            senderName: 'AIW20004141',
            requestID: 'EPY08099J8M75',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'eid 6#Eid_6',
            status: 'failed',
            giftCategory: 'Eid_2',
          },
          {
            amount: '10.00',
            receiverWalletNumber: '10142',
            senderWalletNumber: '20004141',
            receiverName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            trnsDateTime: '2008-04-08T17:05:00',
            bankFeeAmt: null,
            receiverMobile: '0583433324',
            senderMobile: '0523614587',
            feeAmt: null,
            parentRequestID: 'EPY08099J0HWP',
            senderName: 'AIW20004141',
            requestID: 'EPY08099J0HWP',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'eid 5#Eid_5',
            status: 'failed',
            giftCategory: 'Eid_2',
          },
          {
            amount: '7.00',
            receiverWalletNumber: '10142',
            senderWalletNumber: '11202',
            receiverName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            trnsDateTime: '2008-04-08T15:48:00',
            bankFeeAmt: null,
            receiverMobile: '0583433324',
            senderMobile: '0508987485',
            feeAmt: null,
            parentRequestID: 'EPY08099QN652',
            senderName: 'SAHQB ABDULLAH ABDULAHMASAN ALRMOI',
            requestID: 'EPY08099QN652',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Happy eid#Eid_1',
            status: 'executed',
            giftCategory: 'Eid_2',
          },
          {
            amount: '15.00',
            receiverWalletNumber: '10142',
            senderWalletNumber: '20004186',
            receiverName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            trnsDateTime: '2008-04-08T14:31:00',
            bankFeeAmt: null,
            receiverMobile: '0583433324',
            senderMobile: '0509104609',
            feeAmt: null,
            parentRequestID: 'EPY08099RPLGG',
            senderName: 'SAHQB ABDULLAH ABDULAHMASAN ALRMOI',
            requestID: 'EPY08099RPLGG',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Congratulations#Congrat_1',
            status: 'failed',
            giftCategory: 'Eid_2',
          },
        ],
        SENT: [
          {
            amount: '100.00',
            receiverWalletNumber: '',
            senderWalletNumber: '10142',
            receiverName: '',
            trnsDateTime: '2008-04-08T16:42:00',
            bankFeeAmt: null,
            receiverMobile: '',
            senderMobile: '0583433324',
            feeAmt: null,
            parentRequestID: 'EPY08099CTBGT',
            senderName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            requestID: 'EPY08099CTBGT',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Happy eidd#Eid_5',
            status: 'initiated',
            giftCategory: 'Eid_2',
          },
          {
            amount: '10.00',
            receiverWalletNumber: '',
            senderWalletNumber: '10142',
            receiverName: '',
            trnsDateTime: '2008-04-08T14:31:00',
            bankFeeAmt: null,
            receiverMobile: '',
            senderMobile: '0583433324',
            feeAmt: null,
            parentRequestID: 'EPY08099QGJJ1',
            senderName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            requestID: 'EPY08099QGJJ1',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Happy eid#Eid_1',
            status: 'failed',
            giftCategory: 'Eid_2',
          },
          {
            amount: '32.00',
            receiverWalletNumber: '',
            senderWalletNumber: '10142',
            receiverName: '',
            trnsDateTime: '2008-04-08T13:18:00',
            bankFeeAmt: null,
            receiverMobile: '',
            senderMobile: '0583433324',
            feeAmt: null,
            parentRequestID: 'EPY08099J51F5',
            senderName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            requestID: 'EPY08099J51F5',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Ø¹ÙŠØ¯ Ø³Ø¹ÙŠØ¯#Eid_1',
            status: 'executed',
            giftCategory: 'Eid_2',
          },
          {
            amount: '100.00',
            receiverWalletNumber: '',
            senderWalletNumber: '10142',
            receiverName: '',
            trnsDateTime: '2008-04-08T12:09:00',
            bankFeeAmt: null,
            receiverMobile: '',
            senderMobile: '0583433324',
            feeAmt: null,
            parentRequestID: 'EPY08099MB3FR',
            senderName: 'PRABAKARAN BALAKRISHNAN BALAKRISHNAN',
            requestID: 'EPY08099MB3FR',
            vatAmt: null,
            bankVATAmt: null,
            userNotes: 'Happy eid#Eid_1',
            status: 'failed',
            giftCategory: 'Eid_2',
          },
        ],
      },
    },
  },
  successfulResponse: true,
  status: {
    sessionReference: 'SSPAYC5c2207e5333046a780efc88f0d60fc23',
    code: 'I000000',
    requestReference: '00613853255231576649',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
  },
  ok: true,
};

export default walletToWalletTransferMock;
