import images from '@app/assets/images';
import { LocalTransferMockProps } from './transfer-history.interface';

const localTransferMock: LocalTransferMockProps = {
  // TODO need to update this data
  response: {
    transactions: [
      {
        transactionRefNumber: 'EPY233592QXTP',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '1.00',
        transactionRequestType: 'PAY_WALLET',
        transactionRequestTypeDesc: 'Wallet to wallet transfer',
        transactionType: 'DR',
        mobileNumber: '0583968704',
        walletNumber: null,
        nickname: '0583968704',
        bankId: null,
        beneficiaryName: 'Saudi National Bank',
        bankName: 'Saudi National Bank',
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: 'labor send mony back to sponsor',
        transactionDateTime: '2023-12-25T11:00:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: 'Hany Ali Omar Ahmed',
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359DZDL3',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '10.00',
        transactionRequestType: 'PAY_WALLET',
        transactionRequestTypeDesc: 'Wallet to wallet transfer',
        transactionType: 'DR',
        mobileNumber: '0581472589',
        walletNumber: null,
        nickname: 'SAHQB ALRMOI',
        bankId: null,
        beneficiaryName: 'Al Rajhi Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: 'user1',
        transactionDateTime: '2023-12-25T16:59:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: 'صهب عبدالله عبد المحسن الرومى',
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359J1DPB',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '100.00',
        transactionRequestType: 'CIN_SARIE_REV',
        transactionRequestTypeDesc: 'Gift',
        transactionType: 'CR',
        mobileNumber: '0581936578',
        walletNumber: null,
        nickname: 'SAHQB ALRMOI',
        bankId: null,
        beneficiaryName: 'Alinma Bank',
        bankName: 'Saudi National Bank',
        iban: '3246563754673763453465',
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: 'Happy birthday to u#Birthday_1',
        transactionDateTime: '2023-12-25T10:47:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: 'SAHQB ABDULLAH ABDULAHMASAN ALRMOI',
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY233598CJS1',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '200.00',
        transactionRequestType: 'CIN_SARIE_REV',
        transactionRequestTypeDesc: 'Gift',
        transactionType: 'CR',
        mobileNumber: '0581936578',
        walletNumber: null,
        nickname: 'SAHQB ALRMOI',
        bankId: null,
        beneficiaryName: 'Alinma Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: 'Happy eid#Eid_1',
        transactionDateTime: '2023-12-25T10:17:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: 'SAHQB ABDULLAH ABDULAHMASAN ALRMOI',
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY233593L4JD',
        mtcn: null,
        remittanceRefNumber: 'FT432097DMVQ',
        amount: '12.98',
        transactionRequestType: 'CIN_SARIE_REV',
        transactionRequestTypeDesc: 'Inward transfer from Alinma bank',
        transactionType: 'CR',
        mobileNumber: '0568814770',
        walletNumber: null,
        nickname: '0568814770',
        bankId: null,
        beneficiaryName: 'Saudi National Bank',
        bankName: 'Saudi National Bank',
        iban: 'SA2105012000000110295383',
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T16:12:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: null,
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359JCV6W',
        mtcn: null,
        remittanceRefNumber: 'FT43138HH8N8',
        amount: '21.00',
        transactionRequestType: 'CIN_SARIE_REV',
        transactionRequestTypeDesc: 'Inward transfer from Alinma bank',
        transactionType: 'CR',
        mobileNumber: '0568814770',
        walletNumber: null,
        nickname: '0568814770',
        bankId: null,
        beneficiaryName: 'Saudi National Bank',
        bankName: 'Saudi National Bank',
        iban: 'SA2105012000000110295383',
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T08:36:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: null,
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359VFP2B',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '150.00',
        transactionRequestType: 'CIN_SARIE_REV',
        transactionRequestTypeDesc: 'Top-up through Master card',
        transactionType: 'CR',
        mobileNumber: '0568814770',
        walletNumber: null,
        nickname: '0568814770',
        bankId: null,
        beneficiaryName: 'Saudi National Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T11:00:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: null,
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359121ZR',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '49.00',
        transactionRequestType: 'PAY_WALLET',
        transactionRequestTypeDesc: 'Top-up through Master card',
        transactionType: 'DR',
        mobileNumber: '0568814770',
        walletNumber: null,
        nickname: '0568814770',
        bankId: null,
        beneficiaryName: 'Alinma Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T10:44:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: null,
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359CZPRV',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '150.00',
        transactionRequestType: 'PAY_WALLET',
        transactionRequestTypeDesc: 'Wallet top up through Visa card',
        transactionType: 'DR',
        mobileNumber: '0568814770',
        walletNumber: null,
        nickname: '0568814770',
        bankId: null,
        beneficiaryName: 'Al Rajhi Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T10:42:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: null,
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
      {
        transactionRefNumber: 'EPY23359CKT0V',
        mtcn: null,
        remittanceRefNumber: null,
        amount: '10.00',
        transactionRequestType: 'PAY_WALLET',
        transactionRequestTypeDesc: 'Wallet to wallet transfer',
        transactionType: 'DR',
        mobileNumber: '0581936578',
        walletNumber: null,
        nickname: 'SAHQB ALRMOI',
        bankId: null,
        beneficiaryName: 'Al Rajhi Bank',
        bankName: null,
        iban: null,
        terminalId: null,
        terminalDesc: null,
        cardNumber: null,
        cardType: null,
        transactionDescription: null,
        transactionDateTime: '2023-12-25T16:42:00',
        walletTransactionStatus: 'executed',
        feesAmount: '0.00',
        vatAmount: '0.00',
        bankFeesAmount: null,
        bankVatAmount: null,
        giftCategoryTitle: null,
        giftCategoryIconUrl: null,
        giftTemplateId: null,
        giftTemplateUrl: null,
        ftRefNumber: null,
        sadadPaymentRefNumber: null,
        vatInvoiceNumber: null,
        oneCardPriceBeforeVat: 0,
        oneCardVat: 0,
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        showSplitBill: false,
        payrollAmount: null,
        transactionJustfication: null,
        transactionDeductionDescription: null,
        fromMonth: null,
        toMonth: null,
        salaryMonth: null,
        senderName: 'SAHQB ABDULLAH ABDULAHMASAN ALRMOI',
        bonusAmount: null,
        bankImage: images.alinmaBankLogo,
      },
    ],
  },
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'Alinmapay.walletTransactionsInquiry.getTransactions.messege.success',
    sessionReference: 'SSPAYCcb37cf2a8092499288ff1c1144d02960',
    requestReference: '01386623456430044448',
  },
  paginationInfo: { matchedRecords: '42', sentRecords: '26' },
  successfulResponse: true,
  ok: true,
};

export default localTransferMock;
