import { MusanedInquiryMockProps } from './musaned-inquiry.interface';

const musanedInquiryMock: MusanedInquiryMockProps = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
    sessionReference: 'SSPAYC55368cc5a3c9473484d5d16a7f5c2e87',
    requestReference: '06407156540228099016',
  },
  response: {
    sponsorName: 'فاطمه عرار بطي الدوسري',
    sponsorPOINumber: '1122585191',
    sponsorNationality: 'المملكة العربية السعودية',
    sponsorBirthDateHijri: '1419-08-15',
    laborersInfoList: [
      {
        borderNumber: '3707691246',
        name: 'MUNNA PRASAD HAJARI PRASAD',
        poiNumber: '2339846541',
        poiExperationDate: '2025-10-19',
        nationalityAr: 'الهند',
        nationalityEn: 'India',
        nationality: 'India',
        contractNumber: '',
        payrollAmount: '1500',
        lastPaidSalaryDate: '2024:03',
        salarySource: '',
        occupationAr: 'سائق خاص',
        occupationEn: 'personal driver',
        occupation: 'personal driver',
        haveWalletFlag: true,
        mobileNumber: '0589612745',
        countryCode: 'IN',
        walletNumber: '20004114',
      },
      {
        borderNumber: '3128951203',
        name: 'JENNY CAPIRAL  MAREGMEN',
        poiNumber: '2551730472',
        poiExperationDate: '2025-10-06',
        nationalityAr: 'الفلبين',
        nationalityEn: 'Philippines',
        nationality: 'Philippines',
        contractNumber: '4870498',
        payrollAmount: '1500',
        lastPaidSalaryDate: '2024:02',
        salarySource: 'eTawtheeq',
        occupationAr: 'عاملة منزلية',
        occupationEn: 'a house keeper',
        occupation: 'a house keeper',
        haveWalletFlag: false,
        countryCode: 'PH',
      },
      {
        borderNumber: '3094850900',
        name: 'JOSEPHINE  PACING TUBERA',
        poiNumber: '2502000850',
        poiExperationDate: '2025-11-05',
        nationalityAr: 'الفلبين',
        nationalityEn: 'Philippines',
        nationality: 'Philippines',
        contractNumber: '1491370',
        payrollAmount: '1500',
        lastPaidSalaryDate: '2024:07',
        salarySource: 'eTawtheeq',
        occupationAr: 'عاملة منزلية',
        occupationEn: 'a house keeper',
        occupation: 'a house keeper',
        haveWalletFlag: false,
        countryCode: 'PH',
      },
      {
        borderNumber: '3085307282',
        name: 'FAISAL SARWAR MUHAMMAD SARWAR',
        poiNumber: '2516472335',
        poiExperationDate: '2026-03-21',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '',
        payrollAmount: '1300',
        lastPaidSalaryDate: '',
        salarySource: '',
        occupationAr: 'عامل منزلي',
        occupationEn: 'Domestic worker',
        occupation: 'عامل منزلي',
        haveWalletFlag: false,
        countryCode: 'PK',
      },
      {
        borderNumber: '3085307282',
        name: 'FAISAL SARWAR MUHAMMAD SARWAR',
        poiNumber: '2516472335',
        poiExperationDate: '2026-03-21',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '',
        payrollAmount: '1300',
        lastPaidSalaryDate: '',
        salarySource: '',
        occupationAr: 'عامل منزلي',
        occupationEn: 'Domestic worker',
        occupation: 'عامل منزلي',
        haveWalletFlag: true,
        countryCode: 'PK',
      },
      {
        borderNumber: '3087066001',
        name: 'TAQI ULLAH FAZAL MAULA',
        poiNumber: '2509219859',
        poiExperationDate: '2026-01-25',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        paymentStatus: 'Paid',
        contractNumber: '',
        payrollAmount: '1200',
        lastPaidSalaryDate: '2024:10',
        salarySource: '',
        occupationAr: 'سائق خاص',
        occupationEn: 'personal driver',
        occupation: 'سائق خاص',
        haveWalletFlag: true,
        mobileNumber: '0583669747',
        countryCode: 'PK',
        walletNumber: '10588012',
      },
      {
        borderNumber: '3088695121',
        name: 'UMAR FAROOQ MUHAMMAD BOOTA',
        poiNumber: '2522011184',
        poiExperationDate: '2026-06-29',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '2907691',
        payrollAmount: '1200',
        lastPaidSalaryDate: '',
        salarySource: 'eTawtheeq',
        occupationAr: 'سائق خاص',
        occupationEn: 'personal driver',
        occupation: 'سائق خاص',
        haveWalletFlag: false,
        countryCode: 'PK',
      },
    ],
  },
  successfulResponse: true,
};

export default musanedInquiryMock;
