import { MusanedInquiryMockProps } from './musaned-inquiry.interface';

const musanedInquiryMock: MusanedInquiryMockProps = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
    sessionReference: 'SSPAYC55368cc5a3c9473484d5d16a7f5c2e87',
    requestReference: '06407156540228099016',
  },
  response: {
    sponsorName: 'فاطمه عرار بطي الدوسري',
    sponsorPOINumber: '1122585191',
    sponsorNationality: 'المملكة العربية السعودية',
    sponsorBirthDateHijri: '1419-08-15',
    laborersInfoList: [
      {
        borderNumber: '3085307282',
        name: 'FAISAL SARWAR MUHAMMAD SARWAR',
        poiNumber: '2516472335',
        poiExperationDate: '2026-03-21',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '',
        payrollAmount: '1300',
        lastPaidSalaryDate: '',
        salarySource: '',
        occupationAr: 'عامل منزلي',
        occupationEn: 'Domestic worker',
        occupation: 'عامل منزلي',
        haveWalletFlag: false,
        countryCode: 'PK',
      },
      {
        borderNumber: '3085307282',
        name: 'FAISAL SARWAR MUHAMMAD SARWAR',
        poiNumber: '2516472335',
        poiExperationDate: '2026-03-21',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '',
        payrollAmount: '1300',
        lastPaidSalaryDate: '',
        salarySource: '',
        occupationAr: 'عامل منزلي',
        occupationEn: 'Domestic worker',
        occupation: 'عامل منزلي',
        haveWalletFlag: true,
        countryCode: 'PK',
      },
      {
        borderNumber: '3087066001',
        name: 'TAQI ULLAH FAZAL MAULA',
        poiNumber: '2509219859',
        poiExperationDate: '2026-01-25',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        paymentStatus: 'Paid',
        contractNumber: '',
        payrollAmount: '1200',
        lastPaidSalaryDate: '2024:10',
        salarySource: '',
        occupationAr: 'سائق خاص',
        occupationEn: 'personal driver',
        occupation: 'سائق خاص',
        haveWalletFlag: true,
        mobileNumber: '0583669747',
        countryCode: 'PK',
        walletNumber: '10588012',
      },
      {
        borderNumber: '3088695121',
        name: 'UMAR FAROOQ MUHAMMAD BOOTA',
        poiNumber: '2522011184',
        poiExperationDate: '2026-06-29',
        nationalityAr: 'باكستان',
        nationalityEn: 'Pakistan',
        nationality: 'باكستان',
        contractNumber: '2907691',
        payrollAmount: '1200',
        lastPaidSalaryDate: '',
        salarySource: 'eTawtheeq',
        occupationAr: 'سائق خاص',
        occupationEn: 'personal driver',
        occupation: 'سائق خاص',
        haveWalletFlag: false,
        countryCode: 'PK',
      },
    ],
  },
  successfulResponse: true,
};

export default musanedInquiryMock;
