import { CardResponseInterface } from './transaction.interface';
import { ApiResponse } from '../../services.interface';

const cardsListMock: ApiResponse<{ cards: CardResponseInterface[] }> = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'Alinmapay.cardManagement.cardInquiry.getCards.messege.success',
    sessionReference: 'SSPAYC484d81ff92584b9b91c118ec5bd68097',
    requestReference: '09078703162196429898',
  },
  paginationInfo: {
    matchedRecords: '11',
    sentRecords: '10',
  },
  response: {
    cards: [
      {
        cardIndex: '4298752495053545348485151544948555351',
        cardNumber: '4125650033610753',
        cardStatus: '800',
        cardStatusDesc: 'Closed (Declined)',
        cardTypeId: 'IPMC',
        cardTypeDesc: 'Alinma Pay Virtual Card',
        cardClassId: 'IPMP',
        cardClassDesc: 'Alinma Pay Virtual Card',
        expiryDate: '2030-02-28',
        maskedCardNumber: 'xxxx xxxx xxxx 0753',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'SAHQB ALRMOI',
          firstName: 'SAHQB',
          lastName: 'ALRMOI',
        },
        issueDate: '2026-02-06',
        expiryDateMonthYear: '02-2030',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2026-02-06',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752495053545348485148564853485357',
        cardNumber: '4125650030805059',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'IPMC',
        cardTypeDesc: 'Alinma Pay Virtual Card',
        cardClassId: 'IPMP',
        cardClassDesc: 'Alinma Pay Virtual Card',
        expiryDate: '2028-04-30',
        maskedCardNumber: 'xxxx xxxx xxxx 5059',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'SAHQB ALRMOI',
          firstName: 'SAHQB',
          lastName: 'ALRMOI',
        },
        issueDate: '2024-08-07',
        expiryDateMonthYear: '04-2028',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-04-04',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484855484857515156',
        cardNumber: '4286790007009338',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-07-31',
        maskedCardNumber: 'xxxx xxxx xxxx 9338',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-07-11',
        expiryDateMonthYear: '07-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-07-11',
          virtualCard: true,
        },
        physicalCard: false,
      },
      {
        cardIndex: '4298752505654555748484853495055524853',
        cardNumber: '4286790005127405',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-07-31',
        maskedCardNumber: 'xxxx xxxx xxxx 7405',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-07-11',
        expiryDateMonthYear: '07-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-07-11',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484855515552514850',
        cardNumber: '4286790007374302',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-07-31',
        maskedCardNumber: 'xxxx xxxx xxxx 4302',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-07-22',
        expiryDateMonthYear: '07-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-07-22',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484848525052515252',
        cardNumber: '4286790000424344',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-09-30',
        maskedCardNumber: 'xxxx xxxx xxxx 4344',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-09-25',
        expiryDateMonthYear: '09-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-09-25',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484857535655495249',
        cardNumber: '4286790009587141',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-09-30',
        maskedCardNumber: 'xxxx xxxx xxxx 7141',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-09-25',
        expiryDateMonthYear: '09-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-09-25',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484856514955514848',
        cardNumber: '4286790008317300',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-09-30',
        maskedCardNumber: 'xxxx xxxx xxxx 7300',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-09-25',
        expiryDateMonthYear: '09-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-09-25',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484855565250535549',
        cardNumber: '4286790007842571',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-09-30',
        maskedCardNumber: 'xxxx xxxx xxxx 2571',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-09-25',
        expiryDateMonthYear: '09-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-09-25',
          virtualCard: true,
        },
        physicalCard: true,
      },
      {
        cardIndex: '4298752505654555748484848575757495049',
        cardNumber: '4286790000999121',
        cardStatus: '100',
        cardStatusDesc: 'Unrestricted',
        cardTypeId: 'VPPC',
        cardTypeDesc: 'VISA CASHBACK PLATINUM',
        cardClassId: 'VPPP',
        cardClassDesc: 'Platinum Cashback Card',
        expiryDate: '2027-09-30',
        maskedCardNumber: 'xxxx xxxx xxxx 9121',
        cvv2: '000',
        linkedName: {
          title: 'MR',
          embossingName: 'Hany Ahmed',
          firstName: 'Hany',
          lastName: 'Ahmed',
        },
        issueDate: '2024-09-25',
        expiryDateMonthYear: '09-2027',
        creditCardDetails: {
          dueAmount: '0',
          availableBalance: '0',
          cashAvailableBalance: '0',
          extraBalance: '0',
          totalOutstanding: '0',
          creditLimit: '0',
          cashLimit: '0',
          statementIssuanceDate: '',
          nextAnnualFeesDueDate: '2025-09-25',
          virtualCard: true,
        },
        physicalCard: true,
      },
    ] as CardResponseInterface[],
  },
  successfulResponse: true,
};

export default cardsListMock;
