import { TransactionsMockProps } from './transaction.interface';

const transactionMock: any = {
  "status": {
    "code": "I000000",
    "type": "SUCCESS",
    "desc": "Alinmapay.walletTransactionsInquiry.getTransactions.messege.success",
    "sessionReference": "SSPAYCaf2acaf2588149a1b77e5b21a6af8b2b",
    "requestReference": "05520889916933080102"
  },
  "paginationInfo": {
    "matchedRecords": "120",
    "sentRecords": "50"
  },
  "response": {
    "transactions": [
      {
        "transactionRefNumber": "EPY242591B7ZT",
        "amount": "10.00",
        "transactionRequestType": "CIN_CARD_MADA",
        "transactionRequestTypeDesc": "Wallet top up through MADA card",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "transactionDateTime": "2024-09-15T15:10:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "10.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY24249BHBD5",
        "amount": "1.00",
        "transactionRequestType": "CIN_MAZAYA",
        "transactionRequestTypeDesc": "Topup wallet using Akthar Program Points",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "transactionDateTime": "2024-09-05T16:19:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY24249QG030",
        "amount": "0.02",
        "transactionRequestType": "CIN_MAZAYA",
        "transactionRequestTypeDesc": "Topup wallet using Akthar Program Points",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "transactionDateTime": "2024-09-05T15:59:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "0.02",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY24246XN6Q5",
        "amount": "1.00",
        "transactionRequestType": "CIN_MAZAYA",
        "transactionRequestTypeDesc": "Topup wallet using Akthar Program Points",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "transactionDateTime": "2024-09-02T14:55:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY24246Z03GM",
        "amount": "1.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "DR",
        "mobileNumber": "0536042549",
        "nickname": "MOSTAFA AWAD",
        "transactionDescription": "100 sar",
        "transactionDateTime": "2024-09-02T14:50:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY2422805LFG",
        "amount": "1.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "DR",
        "mobileNumber": "0500405290",
        "nickname": "ABDULAZIZ ALNEMER",
        "transactionDateTime": "2024-08-15T17:49:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY2422851R3W",
        "amount": "1.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "CR",
        "mobileNumber": "0582188647",
        "nickname": "ANWAR ABDUALLA",
        "transactionDateTime": "2024-08-15T15:49:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "انور مصطفي انور عبد الله",
        "totalCreditAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY2422813HMT",
        "amount": "1.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "DR",
        "mobileNumber": "0582188647",
        "nickname": "ANWAR ABDUALLA",
        "transactionDateTime": "2024-08-15T15:47:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "1.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24150Z5BDG",
        "amount": "25.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "DR",
        "mobileNumber": "0533743615",
        "nickname": "ABDALLAH TORON",
        "transactionDescription": "TB",
        "transactionDateTime": "2024-05-29T08:59:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "25.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24122BL9YD",
        "amount": "50.00",
        "transactionRequestType": "PAY_WALLET",
        "transactionRequestTypeDesc": "Wallet to wallet transfer",
        "transactionType": "DR",
        "mobileNumber": "0582188647",
        "nickname": "ANWAR ABDUALLA",
        "transactionDateTime": "2024-05-01T13:13:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "50.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY241220J3YL",
        "remittanceRefNumber": "FT24122YDHP1",
        "amount": "50.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "iban": "SA0705012000000110137428",
        "transactionDateTime": "2024-05-01T13:12:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "50.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY2410320C1V",
        "remittanceRefNumber": "20240409265723",
        "amount": "60.00",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 60 purchase was made with VISA card ****4281 at ZAKATALFITER on 09/04 at 10:07",
        "transactionDateTime": "2024-04-09T08:27:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "60.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24043CRDXP",
        "remittanceRefNumber": "20240209741751",
        "amount": "24.00",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 24 purchase was made with VISA card ****4281 at Juice Time on 08/02 at 18:38",
        "transactionDateTime": "2024-02-09T08:52:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "24.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24043D2VQD",
        "remittanceRefNumber": "20240209741670",
        "amount": "68.77",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 68.77 purchase was made with VISA card ****4281 at Pharmacy Outlet on 08/02 at 18:25",
        "transactionDateTime": "2024-02-09T08:52:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "68.77",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24042F66M7",
        "remittanceRefNumber": "20240207727906",
        "amount": "98.88",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 98.88 purchase was made with VISA card ****4281 at Fullel Gasolin Station on 07/02 at 04:11",
        "transactionDateTime": "2024-02-07T10:23:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "98.88",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24039GYKDT",
        "amount": "0.29",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR0.29 Cashback Visa was made with card ****4281 at Juice Time             on 20/08 at 18:38",
        "transactionDateTime": "2024-02-08T21:38:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "0.29",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "Juice Time",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24039NM939",
        "amount": "0.83",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR0.83 Cashback Visa was made with card ****4281 at Pharmacy Outlet        on 20/08 at 18:25",
        "transactionDateTime": "2024-02-08T21:25:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "0.83",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "Pharmacy Outlet",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY2403187HHQ",
        "remittanceRefNumber": "20240127636347",
        "amount": "84.25",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 84.25 purchase was made with VISA card ****4281 at Pharmacy Outlet on 27/01 at 13:51",
        "transactionDateTime": "2024-01-27T13:48:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "84.25",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY240318M909",
        "remittanceRefNumber": "20240126626744",
        "amount": "90.06",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 90.06 purchase was made with VISA card ****4281 at Al Sadhan Trading Company on 26/01 at 11:10",
        "transactionDateTime": "2024-01-26T13:48:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "90.06",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY2403195NZ8",
        "remittanceRefNumber": "20240128637777",
        "amount": "60.00",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 60 purchase was made with VISA card ****4281 at SODAS SPORTS on 27/01 at 17:49",
        "transactionDateTime": "2024-01-28T13:48:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "60.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY240298MLS8",
        "remittanceRefNumber": "20240126626522",
        "amount": "129.67",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 129.67 purchase was made with VISA card ****4281 at AL OTHAIM MARKETS COMPA on 26/01 at 10:33",
        "transactionDateTime": "2024-01-26T08:56:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "129.67",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24029W84XQ",
        "remittanceRefNumber": "20240126627540",
        "amount": "96.00",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 96 purchase was made with VISA card ****4281 at sasco Yarmouk11201 on 26/01 at 13:23",
        "transactionDateTime": "2024-01-26T08:56:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "96.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24029YJ05X",
        "remittanceRefNumber": "20240126627482",
        "amount": "17.00",
        "transactionRequestType": "PAY_VCARD_SETTLE",
        "transactionRequestTypeDesc": "Settlement of digital card purchase",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR 17 purchase was made with VISA card ****4281 at Juice Time on 26/01 at 13:13",
        "transactionDateTime": "2024-01-26T08:56:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "17.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY24027N8L86",
        "amount": "0.72",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR0.72 Cashback Visa was made with card ****4281 at SODAS SPORTS           on 12/27 at 17:49",
        "transactionDateTime": "2024-01-27T20:49:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "0.72",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "SODAS SPORTS",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24027D5V1R",
        "remittanceRefNumber": "FT24027XGTVP",
        "amount": "250.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2024-01-27T19:22:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "250.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY240273FBXP",
        "amount": "1.01",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR1.01 Cashback Visa was made with card ****4281 at Pharmacy Outlet        on 12/27 at 13:51",
        "transactionDateTime": "2024-01-27T16:51:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1.01",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "Pharmacy Outlet",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24026MFGHR",
        "remittanceRefNumber": "FT24026WCXHK",
        "amount": "200.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2024-01-26T16:22:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "200.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY24026GMJN4",
        "amount": "0.20",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR0.20 Cashback Visa was made with card ****4281 at Juice Time             on 12/26 at 13:13",
        "transactionDateTime": "2024-01-26T16:13:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "0.20",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "Juice Time",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24026BYDS0",
        "amount": "1.08",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR1.08 Cashback Visa was made with card ****4281 at Al-Sadhan Trading Comp on 12/26 at 11:10",
        "transactionDateTime": "2024-01-26T14:10:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1.08",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "Al-Sadhan Trading Comp",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24026W05Y7",
        "amount": "1.56",
        "transactionRequestType": "CIN_VISA_CASHBACK",
        "transactionRequestTypeDesc": "Visa Card Cashback amount",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "SAR1.56 Cashback Visa was made with card ****4281 at AL-OTHAIM MARKETS COMP on 12/26 at 10:33",
        "transactionDateTime": "2024-01-26T13:33:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1.56",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT",
        "merchantName": "AL-OTHAIM MARKETS COMP",
        "acquirerCountry": "SA"
      },
      {
        "transactionRefNumber": "EPY24026DBPTV",
        "remittanceRefNumber": "FT24026K5JKG",
        "amount": "300.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2024-01-26T12:50:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "300.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "EPY240058BXDF",
        "amount": "0.00",
        "transactionRequestType": "CARD_VCB_ISSUE",
        "transactionRequestTypeDesc": "Visa Prepaid Card Issuance Fees",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2024-01-05T17:19:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "0.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY233075GXKS",
        "remittanceRefNumber": "FT233070WS8Q",
        "amount": "402.50",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "GSM",
        "transactionDateTime": "2023-11-03T13:20:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "402.50",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY23307JDN5N",
        "remittanceRefNumber": "FT23307ZPQWJ",
        "amount": "809.44",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "ELCT",
        "transactionDateTime": "2023-11-03T13:20:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "809.44",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY23307KT3QN",
        "remittanceRefNumber": "FT23307XPDVC",
        "amount": "123.28",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDescription": "GSM",
        "transactionDateTime": "2023-11-03T13:20:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "123.28",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "EPY23307SL68N",
        "remittanceRefNumber": "FT23307KC3B1",
        "amount": "1335.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "mobileNumber": "0569196930",
        "nickname": "0569196930",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-11-03T13:19:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1335.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "13613653",
        "amount": "5.00",
        "transactionRequestType": "CIN_CASH_BACK",
        "transactionRequestTypeDesc": "AlinmaPay Cashback",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "AlinmaPay Cashback",
        "transactionDateTime": "2023-10-09T16:17:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "5.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "13312543",
        "amount": "836.56",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-10-03T08:57:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "836.56",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "13312544",
        "amount": "402.50",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-10-03T08:57:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "402.50",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "13312565",
        "amount": "115.00",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-10-03T08:57:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "115.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "13312494",
        "amount": "1350.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-10-03T08:55:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1350.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "12311564",
        "amount": "9.70",
        "transactionRequestType": "CIN_CASH_BACK",
        "transactionRequestTypeDesc": "AlinmaPay Cashback",
        "transactionType": "CR",
        "cardNumber": "428679******4281",
        "transactionDescription": "AlinmaPay Cashback",
        "transactionDateTime": "2023-09-07T16:21:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "9.70",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "12167289",
        "amount": "821.03",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-09-03T06:45:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "821.03",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "12167350",
        "amount": "402.50",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-09-03T06:45:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "402.50",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "12167351",
        "amount": "127.42",
        "transactionRequestType": "PAY_BILL",
        "transactionRequestTypeDesc": "SADAD bill Payment",
        "transactionType": "DR",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-09-03T06:45:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "127.42",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "12167332",
        "amount": "1350.00",
        "transactionRequestType": "CIN_ALINMA",
        "transactionRequestTypeDesc": "Inward transfer from Alinma bank",
        "transactionType": "CR",
        "iban": "SA0705012000000110137428",
        "cardNumber": "428679******4281",
        "transactionDateTime": "2023-09-03T06:43:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "1350.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "12049694",
        "amount": "97.01",
        "transactionRequestType": "PAY_VCARD_POS_MADA",
        "transactionRequestTypeDesc": "POS MADA purchase",
        "transactionType": "DR",
        "terminalId": "8166133201197420",
        "cardNumber": "412565******2762",
        "transactionDescription": "SAR 97.01 purchase was made with mada card ****2762 at ALDREES 81",
        "transactionDateTime": "2023-08-31T07:15:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": true,
        "senderName": "اسلام محمد ابراهيم احمد",
        "totalDebitAmount": "97.01",
        "transactionCurrency": "SAR",
        "walletTransactionType": "DEBIT"
      },
      {
        "transactionRefNumber": "12049647",
        "amount": "20.00",
        "transactionRequestType": "CIN_MAZAYA",
        "transactionRequestTypeDesc": "Topup wallet using Akthar Program Points",
        "transactionType": "CR",
        "cardNumber": "412565******2762",
        "transactionDateTime": "2023-08-31T07:14:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "20.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "11371438",
        "amount": "5.00",
        "transactionRequestType": "CIN_CASH_BACK",
        "transactionRequestTypeDesc": "AlinmaPay Cashback",
        "transactionType": "CR",
        "cardNumber": "412565******2762",
        "transactionDescription": "AlinmaPay Cashback",
        "transactionDateTime": "2023-08-07T16:25:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "5.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      },
      {
        "transactionRefNumber": "11371439",
        "amount": "5.00",
        "transactionRequestType": "CIN_CASH_BACK",
        "transactionRequestTypeDesc": "AlinmaPay Cashback",
        "transactionType": "CR",
        "cardNumber": "412565******2762",
        "transactionDescription": "AlinmaPay Cashback",
        "transactionDateTime": "2023-08-07T16:25:00",
        "walletTransactionStatus": "executed",
        "feesAmount": "0.00",
        "vatAmount": "0.00",
        "oneCardPriceBeforeVat": 0,
        "oneCardVat": 0,
        "oneCardPriceAfterVat": 0,
        "showVatInvoice": false,
        "showSplitBill": false,
        "totalCreditAmount": "5.00",
        "transactionCurrency": "SAR",
        "walletTransactionType": "CREDIT"
      }
    ]
  },
  "successfulResponse": true
};
export default transactionMock;
