const TRANSACTION_QUERY_KEYS = Object.freeze({
  GET_CARDS: 'GET_CARDS',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTIONS_MUSANED: 'GET_TRANSACTIONS_MUSANED',
});

export default TRANSACTION_QUERY_KEYS;
