const TRANSACTION_QUERY_KEYS = Object.freeze({
  GET_CARDS: 'GET_CARDS',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_CARDS_TRANSACTIONS: 'GET_CARDS_TRANSACTIONS',
});

export default TRANSACTION_QUERY_KEYS;
