import { TransactionsMockProps } from './transaction.interface';

const transactionMock: TransactionsMockProps = {
  response: {
    transactions: [
      {
        feesAmount: '0.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: null,
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: 'GSM',
        terminalId: null,
        giftTemplateUrl: null,
        senderName: 'Ø¨Ø±Ø§Ø¨Ø§ÙƒØ§Ø±Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù†',
        showSplitBill: true,
        beneficiaryName: 'Fairs Ghulam Hussain',
        bonusAmount: null,
        nickname: null,
        transactionDeductionDescription: null,
        remittanceRefNumber: 'FT24148FV4VK',
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '6.74',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T15:05:00',
        transactionRequestType: 'PAY_BILL',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY08099CD390',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '0.00',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'Pay Bill of SADAD Billers',
        transactionType: 'DR',
        bankId: null,
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
      {
        feesAmount: '0.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: '0583433324',
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: 'Test Sadad',
        terminalId: null,
        giftTemplateUrl: null,
        senderName: null,
        showSplitBill: false,
        beneficiaryName: 'Fairs Ahmed',
        bonusAmount: null,
        nickname: '0583433324',
        transactionDeductionDescription: null,
        remittanceRefNumber: null,
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '0.34',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T15:05:00',
        transactionRequestType: 'CIN_CASH_BACK',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY08099TYJW9',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '0.00',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'AlinmaPay Cashback',
        transactionType: 'CR',
        bankId: null,
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
      {
        feesAmount: '0.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: '0512345679',
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: 'Internal wallet to wallet transfer',
        terminalId: null,
        giftTemplateUrl: null,
        senderName: 'farouk osama farouk',
        showSplitBill: false,
        beneficiaryName: 'Ahmed Ghulam Hussain',
        bonusAmount: null,
        nickname: '0583433324',
        transactionDeductionDescription: null,
        remittanceRefNumber: 'FT123TEST123',
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '100.00',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T11:12:00',
        transactionRequestType: 'BKF_TRANSFER',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY08099WFZX9',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '0.00',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'Internal wallet to wallet transfer',
        transactionType: 'CR',
        bankId: null,
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
      {
        feesAmount: '0.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: '0512345679',
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: 'Internal wallet to wallet transfer',
        terminalId: null,
        giftTemplateUrl: null,
        senderName: 'farouk osama farouk',
        showSplitBill: false,
        beneficiaryName: 'Abdul Rehman',
        bonusAmount: null,
        nickname: '0583433324',
        transactionDeductionDescription: null,
        remittanceRefNumber: 'FT111TEST123',
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '100.00',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T10:57:00',
        transactionRequestType: 'BKF_TRANSFER',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY08099N7FJD',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '0.00',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'Internal wallet to wallet transfer',
        transactionType: 'CR',
        bankId: null,
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
      {
        feesAmount: '0.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: '0512345679',
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: 'Internal wallet to wallet transfer',
        terminalId: null,
        giftTemplateUrl: null,
        senderName: 'farouk osama farouk',
        showSplitBill: false,
        beneficiaryName: 'Fairs Ghulam Hussain',
        bonusAmount: null,
        nickname: '0583433324',
        transactionDeductionDescription: null,
        remittanceRefNumber: 'FT123TEST111',
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '100.00',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T10:29:00',
        transactionRequestType: 'BKF_TRANSFER',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY08099424Y5',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '0.00',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'Internal wallet to wallet transfer',
        transactionType: 'CR',
        bankId: null,
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
      {
        feesAmount: '10.00',
        oneCardPriceAfterVat: 0,
        showVatInvoice: false,
        walletTransactionStatus: 'executed',
        sadadPaymentRefNumber: null,
        mobileNumber: null,
        oneCardPriceBeforeVat: 0,
        payrollAmount: null,
        transactionJustfication: null,
        bankName: null,
        transactionDescription: null,
        terminalId: null,
        giftTemplateUrl: null,
        senderName: 'Ø¨Ø±Ø§Ø¨Ø§ÙƒØ§Ø±Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù† Ø¨Ø§Ù„Ø§ÙƒØ±ÙŠØ´Ù†Ø§Ù†',
        showSplitBill: false,
        beneficiaryName: 'Fairs Ghulam Hussain',
        bonusAmount: null,
        nickname: null,
        transactionDeductionDescription: null,
        remittanceRefNumber: 'FT240433WH9B',
        walletNumber: null,
        terminalDesc: null,
        giftCategoryTitle: null,
        oneCardVat: 0,
        mtcn: null,
        vatInvoiceNumber: null,
        amount: '905.12',
        salaryMonth: null,
        transactionDateTime: '2008-04-08T17:25:00',
        transactionRequestType: 'COUT_EXPRESS',
        cardType: null,
        toMonth: null,
        transactionRefNumber: 'EPY080992X9C3',
        giftTemplateId: null,
        ftRefNumber: null,
        vatAmount: '1.50',
        bankFeesAmount: null,
        transactionRequestTypeDesc: 'Cash-Out Using AlinmaPay Direct',
        transactionType: 'DR',
        bankId: 'UBL',
        bankVatAmount: null,
        iban: null,
        giftCategoryIconUrl: null,
        fromMonth: null,
        cardNumber: null,
      },
    ],
  },
  paginationInfo: {
    matchedRecords: '1997',
    sentRecords: '6',
  },
  successfulResponse: true,
  status: {
    sessionReference: 'SSPAYC5c2207e5333046a780efc88f0d60fc23',
    code: 'I000000',
    requestReference: '03939829382653694670',
    type: 'SUCCESS',
    desc: 'Alinmapay.walletTransactionsInquiry.getTransactions.messege.success',
  },
  ok: true,
};
export default transactionMock;
