const printCardMockResponse = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'Alinmapay.cardManagement.cardInquiry.getCardDetails.messege.success',
    sessionReference: 'SSPAYCd1b555b561d94e4194af411deab46c23',
    requestReference: '03959874518980507723',
  },
  response: {
    cardInfo: {
      cardIndex: '4298752505654555748484857525048524848',
      cardNumber: '4286790009420400',
      cardStatus: '100',
      cardStatusDesc: 'نشط (مع خدمة الشراء عبر الانترنتCVV2)',
      cardTypeId: 'VPPC',
      cardTypeDesc: 'Signature Cashback Card',
      cardClassId: 'VPPP',
      cardClassDesc: 'Signature Cashback Card',
      effectiveDate: '',
      expiryDate: '2027-06-30',
      maskedCardNumber: 'xxxx xxxx xxxx 0400',
      cvv2: '000',
      linkedName: {
        title: 'MR',
        embossingName: 'SAHQB ALRMOI',
        firstName: 'SAHQB',
        lastName: 'ALRMOI',
      },
      issueDate: '2024-06-03',
      expiryDateMonthYear: '06-2027',
      creditCardDetails: {
        dueAmount: '0',
        paymentDueDate: '',
        availableBalance: '0',
        cashAvailableBalance: '0',
        extraBalance: '0',
        totalOutstanding: '0',
        creditLimit: '0',
        cashLimit: '0',
        statementIssuanceDate: '',
        nextAnnualFeesDueDate: '2025-06-03',
        virtualCard: false,
      },
      nickname: '',
      monthlyCashbackAmt: '',
      totalCashbackAmt: '',
      nextAnnualFeeDate: '',
      nextAnnualFeeAmt: '',
      nextAnnualFeeVAT: '',
      physicalCard: true,
      reissueDue: false,
      annualFeeDue: false,
    },
  },
  successfulResponse: true,
};

export default printCardMockResponse;
