const getDynamicFieldsMockResponse = {
  response: {
    showbillNumbertHint: false,
    billNumberMinimumWidth: 10,
    dynamicFields: [
      {
        minAmount: null,
        parentIndex: null,
        onlyHijri: null,
        type: 'number',
        required: true,
        lovFilter3: null,
        billIdType: null,
        childIndex: null,
        lovFilter2: null,
        maxAmount: null,
        value: '2521274197',
        lovFilter1: null,
        maxWidth: 10,
        allowedValues: null,
        integrationTagName: 'BeneficiaryId.OfficialId',
        hintEn: null,
        index: 'BeneficiaryId.OfficialId',
        minWidth: 10,
        label: 'Violator ID',
        hintAr: null,
        hijriType: null,
        dateCompareOperation: null,
        requiredInPaymentOrRefund: 'payment',
        orderIndex: '1',
        lovList: null,
        lOVType: null,
      },
      {
        minAmount: null,
        parentIndex: null,
        onlyHijri: null,
        type: 'listOfValue',
        required: true,
        lovFilter3: null,
        billIdType: null,
        childIndex: null,
        lovFilter2: null,
        maxAmount: null,
        value: '86',
        lovFilter1: null,
        maxWidth: 32,
        allowedValues: null,
        integrationTagName: 'BeneficiaryId.OfficialIdType',
        hintEn: null,
        index: 'BeneficiaryId.OfficialIdType',
        minWidth: 1,
        label: 'ID Type',
        hintAr: null,
        hijriType: null,
        dateCompareOperation: null,
        requiredInPaymentOrRefund: 'payment',
        orderIndex: '2',
        lovList: [
          {
            code: 'BIS',
            addtionalAttribute1: 'رقم المنشأة',
            desc: 'Business ID',
          },
          {
            code: 'IQA',
            addtionalAttribute1: 'رقم الإقامة',
            desc: 'Iqama ID',
          },
          {
            code: 'NAT',
            addtionalAttribute1: 'رقم الهوية الوطنية',
            desc: 'National ID',
          },
          {
            code: 'PAS',
            addtionalAttribute1: 'رقم جواز خليجي',
            desc: 'GCC Passport',
          },
        ],
        lOVType: '315',
      },
      {
        minAmount: null,
        parentIndex: null,
        onlyHijri: null,
        type: 'number',
        required: true,
        lovFilter3: null,
        billIdType: null,
        childIndex: null,
        lovFilter2: null,
        maxAmount: null,
        value: null,
        lovFilter1: null,
        maxWidth: 10,
        allowedValues: null,
        integrationTagName: 'Beneficiary.OfficialId',
        hintEn: null,
        index: 'Beneficiary.OfficialId',
        minWidth: 10,
        label: 'Violator ID',
        hintAr: null,
        hijriType: null,
        dateCompareOperation: null,
        requiredInPaymentOrRefund: 'refund',
        orderIndex: '3',
        lovList: null,
        lOVType: null,
      },
      {
        minAmount: null,
        parentIndex: null,
        onlyHijri: null,
        type: 'listOfValue',
        required: true,
        lovFilter3: null,
        billIdType: null,
        childIndex: null,
        lovFilter2: null,
        maxAmount: null,
        value: null,
        lovFilter1: null,
        maxWidth: 32,
        allowedValues: null,
        integrationTagName: 'Beneficiary.OfficialIdType',
        hintEn: null,
        index: 'Beneficiary.OfficialIdType',
        minWidth: 1,
        label: 'ID Type',
        hintAr: null,
        hijriType: null,
        dateCompareOperation: null,
        requiredInPaymentOrRefund: 'refund',
        orderIndex: '4',
        lovList: [
          {
            code: 'BIS',
            addtionalAttribute1: 'رقم المنشأة',
            desc: 'Business ID',
          },
          {
            code: 'IQA',
            addtionalAttribute1: 'رقم الإقامة',
            desc: 'Iqama ID',
          },
          {
            code: 'NAT',
            addtionalAttribute1: 'رقم الهوية الوطنية',
            desc: 'National ID',
          },
          {
            code: 'PAS',
            addtionalAttribute1: 'رقم جواز خليجي',
            desc: 'GCC Passport',
          },
        ],
        lOVType: '315',
      },
    ],
    billNumberLabel: 'Violator ID',
    customerIdType: {
      fieldIndex: 'BeneficiaryId.OfficialIdType',
      value: '86',
    },
    billNumberMaximumWidth: 10,
    customerIdNumber: {
      fieldIndex: 'BeneficiaryId.OfficialId',
      value: '2521274197',
    },
  },
  successfulResponse: true,
  status: {
    sessionReference: 'SSPAYC0f6c1165e9fb4c70b39530f8137b509f',
    code: 'I000000',
    requestReference: '02461994742498236274',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
  },
};

export default getDynamicFieldsMockResponse;
