const images = {
  cards: require('./cards.png'),
  logoAlinma: require('./LogoAlinma.png'),
  globe: require('./globe.png'),
  money: require('./money.png'),
  logo: require('./logo.png'),
  logoSmall: require('./logo-small.png'),
  profile: require('./profileImage.png'), // Profile image on top Navigation
  nifaz: require('./nifaz.png'),
  currency: require('./currency.png'),
  noon: require('./noon.png'),
  line: require('./line.png'),
  shpingCart: require('./shoping-cart.png'),
  menu: require('./menu.png'),
  card: require('./card.png'),
  nafathLogo: require('./nafath-logo.png'),
  logoTab: require('./logoTab.png'),
  codeBar: require('./codebar.png'),
  userRemoveImage: require('./user-remove.png'),
  blackLogo: require('./blackLogo.png'),
  noRecordBox: require('./no-record-box.png'),
  suggestionAd: require('./suggestion-ad.png'),
  shortHandDeitCard: require('./short_hand_debit_card.png'),
  shortHandPlatinuimCard: require('./short_hand_platinum_card.png'),
  shortHandSignatureCard: require('./short_hand_signature_card.png'),
  gradientLogo: require('./gradient_logo.png'),
  scannerMarker: require('./scanner-marker.png'),
  alinmaP: require('./logo-icon-gradient.png'),
  visa: require('./visa.png'),
  visaWhite: require('./visa-white.png'),
  textLogoLight: require('./text-logo-light.png'),
  classicBg: require('./classic-bg.png'),
  platinumBg: require('./platinum-bg.png'),
  signatureBg: require('./signature-bg.png'),
  signature: require('./signature-cover.png'),
  platinum: require('./platinum-cover.png'),
  mada: require('./mada.png'),
  mada_cover: require('./mada-cover.png'),
  logoIconGradient: require('./logo-icon-gradient.png'),
  visaIcon: require('./visa-icon.png'),
  madaIcon: require('./mada-icon.png'),
  cashback: require('./cashback.png'),
 classicBackground: require('./card-circlular.png'),
  addAppleWallet: require('./add-apple-wallet.png'),
  appleWallet: require('./apple-wallet.png'),
  platinumCard: require('./platinum-card.png'),
  signatueCard: require('./signature-card.png'),
  master: require('./master.png'),
  dateCard: require('./dateCard.png'),
  cvvCard: require('./cvvCard.png'),
  visa: require('./visa.png'),
  securityCard: require('./security-card.png'),
};

export default images;
