import { transactionOperations, transactionTypes } from '@app/enums/transaction-types.enum';
import { IPayTransactionItemProps } from './component/ipay-transaction.interface';

const historyData: IPayTransactionItemProps[] = [
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.SEND_MONEY,
    type: transactionOperations.CREDIT,
    amount: '250',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.RECEIVED_MONEY,
    type: transactionOperations.DEBIT,
    amount: '250',
    sender: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Thank you Adam',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-02T13:00:00+05:00').toString(),
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.POS_PURCHASE,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    merchant_name: 'Amazon',
    fee: '0.00 SAR',
    vat: '6.32 SAR',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-03T14:00:00+05:00').toString(),
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.E_COMMERCE,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    merchant_name: 'Amazon',
    fee: '13.0 SAR',
    vat: '0.00 SAR',
    acquire_country: 'USA',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-04T15:00:00+05:00').toString(),
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.CASHBACK,
    type: transactionOperations.DEBIT,
    amount: '300',
    card: 'Mada Debit Card **** 1111',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-05T16:00:00+05:00').toString(),
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.VISA_SIGNATURE_CARD_INSURANCE,
    type: transactionOperations.CREDIT,
    amount: '300',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-06T17:00:00+05:00').toString(),
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.ATM,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    atm_location: 'Al Takhassousi',
    atm_type: 'Car',
    transaction_date: new Date('2024-07-07T18:00:00+05:00').toString(),
    ref_number: 'FTA35346',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.CREDIT,
    amount: '200',
    sender: 'Ahmed Mohamed',
    receiver: 'Omar Abdulrahman',
    bank_name: 'Alinma Bank',
    receivers_iban: 'SA234754746326t34347',
    note: 'Hello Ahmed',
    fee: '0.50 SAR',
    vat: '0.08 SAR',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-08T19:00:00+05:00').toString(),
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.DEBIT,
    amount: '200',
    sender: 'Ahmed Mohamed',
    bank_name: 'Alinma Bank',
    senders_iban: 'SA234754746326t34347',
    note: 'Hello Omar',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-09T20:00:00+05:00').toString(),
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.APPLE_PAY_TOP_UP,
    type: transactionOperations.DEBIT,
    amount: '300',
    ref_number: 'FTA35346',
    transaction_date: new Date('2024-07-10T21:00:00+05:00').toString(),
  },
];

export default historyData;
