import { transactionOperations, transactionTypes } from '@app/enums/transaction-types.enum';
import { IPayTransactionItemProps } from './component/ipay-transaction.interface';

const historyData: IPayTransactionItemProps[] = [
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.SEND_MONEY,
    type: transactionOperations.CREDIT,
    amount: '250',
    transaction_date: '14/03/2024 - 14:30',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.RECEIVED_MONEY,
    type: transactionOperations.DEBIT,
    amount: '250',
    transaction_date: '15/03/2024 - 15:30',
    sender: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Thank you Adam',
    ref_number: 'FTA35346',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.POS_PURCHASE,
    type: transactionOperations.CREDIT,
    amount: '200',
    transaction_date: '16/03/2024 - 16:30',
    card: 'Mada Debit Card **** 1111',
    merchant_name: 'Amazon',
    fee: '0.00',
    vat: '6.32',
    ref_number: '',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.E_COMMERCE,
    type: transactionOperations.CREDIT,
    amount: '200',
    transaction_date: '17/03/2024 - 17:30',
    card: '',
    merchant_name: '',
    fee: '',
    vat: '',
    acquire_country: '',
    ref_number: '',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.CASHBACK,
    type: transactionOperations.DEBIT,
    amount: '300',
    transaction_date: '18/03/2024 - 18:30',
    card: '',
    ref_number: '',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.VISA_SIGNATURE_CARD_INSURANCE,
    type: transactionOperations.CREDIT,
    amount: '300',
    transaction_date: '18/03/2024 - 18:31',
    ref_number: '',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.ATM,
    type: transactionOperations.CREDIT,
    amount: '200',
    transaction_date: '16/03/2024 - 16:31',
    card: '',
    atm_location: '',
    atm_type: '',
    ref_number: '',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.CREDIT,
    amount: '200',
    transaction_date: '17/03/2024 - 17:32',
    sender: '',
    receiver: '',
    bank_name: '',
    receivers_iban: '',
    note: '',
    fee: '',
    vat: '',
    ref_number: '',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.DEBIT,
    amount: '200',
    transaction_date: '17/03/2024 - 17:33',
    sender: '',
    receiver: '',
    bank_name: '',
    receivers_iban: '',
    note: '',
    fee: '',
    vat: '',
    ref_number: '',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.APPLE_PAY_TOP_UP,
    type: transactionOperations.DEBIT,
    amount: '300',
    transaction_date: '18/03/2024 - 18:35',
    ref_number: '',
  },
];

export default historyData;
