import { transactionOperations, transactionTypes } from '@app/enums/transaction-types.enum';
import { IPayTransactionItemProps } from './component/ipay-transaction.interface';

const historyData: IPayTransactionItemProps[] = [
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.SEND_MONEY,
    type: transactionOperations.CREDIT,
    amount: '250',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transaction_date: '14/03/2024 - 14:30',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.RECEIVED_MONEY,
    type: transactionOperations.DEBIT,
    amount: '250',
    sender: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Thank you Adam',
    ref_number: 'FTA35346',
    transaction_date: '15/03/2024 - 15:30',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.POS_PURCHASE,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    merchant_name: 'Amazon',
    fee: '0.00',
    vat: '6.32',
    ref_number: 'FTA35346',
    transaction_date: '16/03/2024 - 16:30',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.E_COMMERCE,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    merchant_name: 'Amazon',
    fee: '13.0',
    vat: '0.00',
    acquire_country: 'USA',
    ref_number: 'FTA35346',
    transaction_date: '16/03/2024 - 16:39',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.CASHBACK,
    type: transactionOperations.DEBIT,
    amount: '300',
    card: 'Mada Debit Card **** 1111',
    ref_number: 'FTA35346',
    transaction_date: '17/03/2024 - 17:30',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.VISA_SIGNATURE_CARD_INSURANCE,
    type: transactionOperations.CREDIT,
    amount: '300',
    ref_number: 'FTA35346',
    transaction_date: '18/03/2024 - 18:31',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.ATM,
    type: transactionOperations.CREDIT,
    amount: '200',
    card: 'Mada Debit Card **** 1111',
    atm_location: 'Al Takhassousi',
    atm_type: 'Car',
    ref_number: 'FTA35346',
    transaction_date: '16/03/2024 - 16:31',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.CREDIT,
    amount: '200',
    sender: 'Ahmed Mohamed',
    receiver: 'Omar Abdulrahman',
    bank_name: 'Alinma Bank',
    receivers_iban: 'SA234754746326t34347',
    note: 'Hello Ahmed',
    fee: '0.50',
    vat: '0.08',
    ref_number: 'FTA35346',
    transaction_date: '17/03/2024 - 17:32',
  },
  {
    name: 'Ahmed Mohamed',
    transaction_type: transactionTypes.LOCAL_TRANSFER,
    type: transactionOperations.DEBIT,
    amount: '200',
    sender: 'Ahmed Mohamed',
    receiver: 'Omar Abdulrahman',
    bank_name: 'Alinma Bank',
    receivers_iban: 'SA234754746326t34347',
    note: 'Hello Omar',
    fee: '0.58',
    vat: '0.08',
    ref_number: 'FTA35346',
    transaction_date: '17/03/2024 - 17:33',
  },
  {
    name: 'Omar Abdulrahman',
    transaction_type: transactionTypes.APPLE_PAY_TOP_UP,
    type: transactionOperations.DEBIT,
    amount: '300',
    ref_number: 'FTA35346',
    transaction_date: '18/03/2024 - 18:35',
  },
];

export default historyData;
