import { GetBillersResponseTypes } from './get-billers.interface';

const getBillersMockResponse: GetBillersResponseTypes = {
  response: {
    billersList: [
      {
        billerId: '001',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Communications',
        billerType: '1',
        billerDesc: '001 - STC',
        typeOfPayment: '1',
        billerCode: 'STC',
      },
      {
        billerId: '002',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Public Services',
        billerType: '3',
        billerDesc: '002 - Saudi Electric Company',
        typeOfPayment: '1',
        billerCode: 'SEC',
      },
      {
        billerId: '003',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '003 - Tawuniya',
        typeOfPayment: '1',
        billerCode: 'Tawuniya',
      },
      {
        billerId: '004',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Public Services',
        billerType: '3',
        billerDesc: '004 - Marafiq',
        typeOfPayment: '2',
        billerCode: 'Marafiq',
      },
      {
        billerId: '005',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Communications',
        billerType: '1',
        billerDesc: '005 - Mobily',
        typeOfPayment: '2',
        billerCode: 'Mobily',
      },
      {
        billerId: '006',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Municipalities',
        billerType: '4',
        billerDesc: '006 - Madinah Municipality',
        typeOfPayment: '1',
        billerCode: 'AMMD',
      },
      {
        billerId: '007',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '007 - Home PC Initiative',
        typeOfPayment: '1',
        billerCode: 'SAHCI',
      },
      {
        billerId: '008',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '008 - Qiyas',
        typeOfPayment: '1',
        billerCode: 'Qiyas',
      },
      {
        billerId: '009',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '009 - King Abdulaziz Univercity',
        typeOfPayment: '1',
        billerCode: 'KAU',
      },
      {
        billerId: '010',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Municipalities',
        billerType: '4',
        billerDesc: '010 - Riyadh Municipality',
        typeOfPayment: '1',
        billerCode: 'MOR',
      },
      {
        billerId: '011',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '011 - Sama Lel Tayaran',
        typeOfPayment: '1',
        billerCode: 'Fly Sama',
      },
      {
        billerId: '013',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Ministries and Commisions',
        billerType: '5',
        billerDesc: '013 - Ministry of Commerce',
        typeOfPayment: '1',
        billerCode: 'MC',
      },
      {
        billerId: '014',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Communications',
        billerType: '1',
        billerDesc: '014 - STC Specialized',
        typeOfPayment: '1',
        billerCode: 'STCSC',
      },
      {
        billerId: '015',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Public Services',
        billerType: '7',
        billerDesc: '015 - Water Services',
        typeOfPayment: '1',
        billerCode: 'MEWA',
      },
      {
        billerId: '016',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Banks',
        billerType: '2',
        billerDesc: '016 - AlAhli Finance and Credit Cards',
        typeOfPayment: '1',
        billerCode: 'NCB CC',
      },
      {
        billerId: '017',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Other billers',
        billerType: '6',
        billerDesc: '017 - Arab Open University',
        typeOfPayment: '0',
        billerCode: 'AOU',
      },
      {
        billerId: '018',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Banks',
        billerType: '2',
        billerDesc: '018 - American Express',
        typeOfPayment: '1',
        billerCode: 'AMEX',
      },
      {
        billerId: '019',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Ministries and Commisions',
        billerType: '5',
        billerDesc: '019 - Jeddah Chamber of Commerce and Industry',
        typeOfPayment: '1',
        billerCode: 'JCCI',
      },
      {
        billerId: '020',
        isrefundAllowed: false,
        billIdType: '',
        billerServices: '',
        billerTypeDesc: 'Ministries and Commisions',
        billerType: '5',
        billerDesc: '020 - General Authority of Zakat and Tax',
        typeOfPayment: '1',
        billerCode: 'ZATCA',
      },
    ],
  },
  successfulResponse: true,
  status: {
    sessionReference: 'SSPAYC7a09163e0c854e5fa40b68231e35b1d3',
    code: 'I000000',
    requestReference: '03006772033783628619',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
  },
};

export default getBillersMockResponse;
