const icons = {
  ARROW_RIGHT: 'arrow-right',
  ARROW_LEFT: 'arrow-left',
  HEADER_BACK: 'arrow-left-1',
  GLOBAL: 'global',
  logout: 'logout',
  right_greater_icon: 'arrow-right-1',
  arrow_circle_down: 'arrow-circle-down',
  arrow_down: 'arrow-down',
  close: 'close-square',
  tick_square: 'tick-square',
  user: 'user',
  warning: 'warning-2',
  add: 'add',
  bell_icon: 'notification-bing1',
  eye: 'eye',
  arrow_right_square: 'arrow-square-right',
  menu: 'menu-1',
  rearrange: 'menu',
  info_fetch: 'info-fetch',
  gift: 'gift',
  global_1: 'global1',
  card: 'card',
  receipt_text: 'receipt-text',
  send_money: 'Custom-send-money-two-tone',
  money_request: 'Custom-money-request-two-tone',
  user_tag: 'user-tag',
  calculator: 'calculator',
  scanner: 'scanner',
  share: 'send-312',
  copy: 'copy',
  copy_success: 'copy-success',
  back_btn_icon: 'arrow-left-1',
  CHECKED: 'left-list-check"',
  ARROW_RIGHT_DEFAULT: 'arrow-right-1',
  save: 'receive-square-23',
  shield_tick: 'shield-tick',
  danger: 'danger',
  clock_1: 'clock-1',
};

export default icons;
