const icons = {
  ARROW_RIGHT: 'arrow-right',
  ARROW_LEFT: 'arrow-left',
  HEADER_BACK: 'arrow-left-1',
  GLOBAL: 'global1',
  CHECKED: 'left-list-check"',
  ARROW_RIGHT_DEFAULT: 'arrow-right-1',
  user: 'user1',
  shield_tick: 'shield-tick',
  logout: 'logout',
  right_greater_icon: 'arrow-right-1',
  arrow_circle_down: 'arrow-circle-down',
  arrow_down: 'arrow-down',
  close: 'close-square',
  tick_square: 'tick-square1',
  warning: 'warning-2',
  add: 'add',
  bell_icon: 'notification-bing1',
  eye: 'eye',
  arrow_right_square: 'arrow-square-right',
  menu: 'menu-1',
  rearrange: 'menu',
  tick_mark_default: 'tick-check-mark-default',
  left_list_icon: 'left-list-check',
  heart: 'heart',
};

export default icons;
