import { GetBillersResponseTypes } from './get-billers.interface';

const getBillersMockResponse: GetBillersResponseTypes = {
  status: {
    code: 'I000000',
    type: 'SUCCESS',
    desc: 'retail.msg.default.success',
    sessionReference: 'SSPAYCc79d2f01e8284eeeab9ddd53797cc29d',
    requestReference: '07651196661975283378',
  },
  response: {
    billersList: [
      {
        billerId: '091',
        billerDesc: 'Driving License',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'DL',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '092',
        billerDesc: 'Saudi Passports',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'SP',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '093',
        billerDesc: 'Traffic Violation',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '1',
        isrefundAllowed: false,
        billerType: '7',
        billerCode: 'TV',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '094',
        billerDesc: 'Motor Vehicle',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'MV',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '095',
        billerDesc: 'Labor Importation',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'LI',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '096',
        billerDesc: 'Civil Registration',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'CR',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '126',
        billerDesc: 'National Platform for Violations',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: false,
        billerType: '7',
        billerCode: 'NPV',
        billerServices: null,
        billIdType: null,
      },
      {
        billerId: '127',
        billerDesc: 'Entry Ports Payments',
        billerTypeDesc: 'Ministry of the Interior (MOI)',
        typeOfPayment: '0',
        isrefundAllowed: true,
        billerType: '7',
        billerCode: 'DC',
        billerServices: null,
        billIdType: null,
      },
    ],
  },
  successfulResponse: true,
};

export default getBillersMockResponse;
