import {
  Countires,
  TransactionMedium,
  TransactionOperations,
  TransactionTypes,
  TransactionsStatus,
} from '@app/enums/transaction-types.enum';
import { InternationalTransferHistoryDataProps } from './international-transfer-history.interface';

const internationalTransferHistoryData: InternationalTransferHistoryDataProps[] = [
  {
    status: TransactionsStatus.REJECTED,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.WESTERN_UNION,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REJECTED,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.PAID,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REFUND,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '1200',
    payrollAmount: '89182',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalDebitAmount: '1200',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.PENDING,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REFUND,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalDebitAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REJECTED,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REFUND,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.WESTERN_UNION,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '900',
    payrollAmount: '66887',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '900',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REFUND,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.ALINMAPAY_DIRECT,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '1000',
    payrollAmount: '74319',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalCreditAmount: '1000',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
  {
    status: TransactionsStatus.REJECTED,
    transactionRequestType: 'International Transfer',
    transactionMedium: TransactionMedium.WESTERN_UNION,
    nickname: 'Adel Sami',
    transactionType: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    beneficiaryName: 'Adam Ahmed',
    country: Countires.PAKISTAN,
    iban: 'SA380019000500000000263180',
    bankName: 'HBL',
    phoneNumber: '+923000330099',
    transferReason: 'Living Expense',
    amount: '670',
    payrollAmount: '49793',
    exchangeRate: '12.69',
    includeFees: 'Yes',
    vatAmount: '10',
    bankFeesAmount: '10',
    promocode: 'Active',
    totalDebitAmount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    note: 'Hello Ahmed',
    remittanceRefNumber: '276423786423786',
    refNumber: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
  },
];

export default internationalTransferHistoryData;
