import {
  TransactionMedium,
  TransactionOperations,
  TransactionTypes,
  TransactionsStatus,
} from '@app/enums/transaction-types.enum';
import { CombinedTransactionItemProps } from '../transaction-history/component/ipay-transaction.interface';

const internationalTransferHistoryData: CombinedTransactionItemProps[] = [
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REJECTED,
    transaction_medium: TransactionMedium.WESTERN_UNION,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REJECTED,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.PAID,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    country_flag: 'ur',
    amount: '1200',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REFUND,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.PENDING,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REFUND,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REJECTED,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '900',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REFUND,
    transaction_medium: TransactionMedium.WESTERN_UNION,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.CASH_PICKUP,
    type: TransactionOperations.CREDIT,
    country_flag: 'ur',
    amount: '1000',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REFUND,
    transaction_medium: TransactionMedium.ALINMAPAY_DIRECT,
  },
  {
    nickname: 'Adel Sami',
    transaction_type: TransactionTypes.BANK_TRANSFER,
    type: TransactionOperations.DEBIT,
    country_flag: 'ur',
    amount: '670',
    sender: 'Adam Ahmad',
    receiver: 'Ahmed Mohamed',
    transfer_reason: 'Living Expense',
    note: 'Hello Ahmed',
    ref_number: 'FTA35346',
    transactionDateTime: new Date('2024-07-01T12:00:00+05:00').toString(),
    status: TransactionsStatus.REJECTED,
    transaction_medium: TransactionMedium.WESTERN_UNION,
  },
];

export default internationalTransferHistoryData;
